# Generated by Django 3.0.7 on 2023-08-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20230805_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_tittle',
            new_name='car_title',
        ),
    ]
